### ISSUE TITLE
Heka published should handle dynamic metrics in a proper/standard way

### ISSUE THREAD

**Issue by obourdon** [intelsdi-x/snap-plugin-publisher-heka#10]
The current plugin implementation uses [this Go code](https://github.com/intelsdi-x/snap-plugin-publisher-heka/blob/master/snapheka/snapheka_client.go#L90-L114) for converting a Snap metric into an Heka message.

Here is an example of Heka message produced by this code:

```C
:Uuid: 64727217-9546-4941-BCEB-75EDC2076
:Timestamp: 2016-06-15 06:55:04.415659520 +0000 UTC
:Type: snap.heka
:Logger: snap.heka.logger
:Severity: 6
:Payload:[
   {"namespace":[{"Value":"intel","Description":"","Name":""}
   {"Value":"procfs","Description":"","Name":""},
   {"Value":"disk","Description":"","Name":""},{"Value":"vda1","Description":"","Name":""},
   {"Value":"merged_read","Description":"","Name":""}],
   "last_advertised_time":"0001-01-01T00:00:00Z","version":0,"config":null,"data":0,
   "tags":{"plugin_running_on":"lma-3n24k"},"Unit_":"","description":"","timestamp":"2016-06-15T06:55:04.358782575Z"}]
:EnvVersion: <nil>
:Pid: 135
:Hostname: lma-3n24k
:Fields:
	| name:namespace type:0 representation: value:intel.procfs.disk.vda1.merged_read
	| name:data type:3 representation: value:0
	| name:source type:0 representation: value:unknown_host
	| name:version type:2 representation: value:0
	| name:timestamp type:2 representation: value:1.4659737043588e+18
```

The major problem with this message format is that it doesn’t includes fields for the dynamic elements of dynamic metrics. In our example “vda1” is the value of a dynamic element whose name is “disk”. In InfluxDB we will want to store “disk=vda1” as a tag. For example:

```C
intel.procfs.disk.merged_read,disk=vda1 value=0 1.4659737043588e+18
```

The current Heka message format used does not allow that, so it should be changed.

# Proposed change

**Dynamic Namespace Elements**

Using our previous example, for “disk=vda1” to be used as an InfluxDB tag the Heka message format must be changed. This is what the Heka message should look like:

```C
:Uuid: 64727217-9546-4941-BCEB-75EDC2076
:Timestamp: 2016-06-15 06:55:04.415659520 +0000 UTC
:Type: snap.heka
:Logger: snap.heka.logger
:Severity: 6
:Payload:[
   {"namespace":[{"Value":"intel","Description":"","Name":""},
   {"Value":"procfs","Description":"","Name":""},{"Value":"disk","Description":"","Name":""},
   {"Value":"vda1","Description":"","Name":""},
   {"Value":"merged_read","Description":"","Name":""}],
   "last_advertised_time":"0001-01-01T00:00:00Z","version":0,"config":null,"data":0,
   "tags":{"plugin_running_on":"lma-3n24k"},"Unit_":"","description":"","timestamp":"2016-06-15T06:55:04.358782575Z"}]
:EnvVersion: <nil>
:Pid: 135
:Hostname: lma-3n24k
:Fields:
	| name:name type:0 representation: value:intel.procfs.disk.merged_read
	| name:value type:3 representation: value:0
	| name:timestamp type:2 representation: value:1.4659737043588e+18
	| name:disk type:0 representation: value:vda1
	| name:dimensions type:3 representation: value:disk
```

One the Field is “disk”, whose value is “vda1”. With this we will able to extract InfluxDB tags out of Snap dynamic elements.

**Implementation note**: 

The “dimensions” field will actually be an array of strings. This is how this field can be created and populated using the Heka message API:

```C
field, err := message.NewField(“dimensions”, “foo”, “”)
if err == nil { 
    field.AddValue(“bar”)
    field.AddValue(“baz”)
}
```

This creates a field named “dimensions” whose value is an array of three strings (“foo”, “bar” and “baz”).

**Tags**

The user may set tags in his workflow definition (user-defined tags). For [example using this JSON file](https://github.com/intelsdi-x/snap/blob/7e41c44c284bc5ee411ac01510733016d0d8b148/scheduler/wmap/sample/1.json#L15-L22)

Tags will be handled as dynamic elements, and added as dimension fields to the Heka message. For example:

```C
:Uuid: 64727217-9546-4941-BCEB-75EDC2076
:Timestamp: 2016-06-15 06:55:04.415659520 +0000 UTC
:Type: snap.heka
:Logger: snap.heka.logger
:Severity: 6
:Payload:[
   {"namespace":[{"Value":"intel","Description":"","Name":""},
   {"Value":"procfs","Description":"","Name":""},{"Value":"disk","Description":"","Name":""},
   {"Value":"vda1","Description":"","Name":""},
   {"Value":"merged_read","Description":"","Name":""}],
   "last_advertised_time":"0001-01-01T00:00:00Z","version":0,"config":null,"data":0,
   "tags":{"plugin_running_on":"lma-3n24k"},"Unit_":"","description":"","timestamp":"2016-06-15T06:55:04.358782575Z"}]
:EnvVersion: <nil>
:Pid: 135
:Hostname: lma-3n24k
:Fields:
	| name:name type:0 representation: value:intel.procfs.disk.merged_read
	| name:value type:3 representation: value:0
	| name:timestamp type:2 representation: value:1.4659737043588e+18
	| name:disk type:0 representation: value:vda1
	| name:tag1 type:0 representation: value:val1
	| name:dimensions type:3 representation: value:disk,tag1
```

**Comment by obourdon** [comment]
Please note that a 1st draft implementation has been done in [my private forked repository](https://github.com/obourdon/snap-plugin-publisher-heka/tree/all_in_1) and is currently under testing

**Comment by marcin-krolik** [comment]
@obourdon If I understand your case correctly, you intend to "transform" dynamic namespace elements to tags. This issue can be handled quite easily with [this](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/blob/master/influx/influx.go#L163-L176) or with [plugin utility](https://github.com/intelsdi-x/snap-plugin-utilities/blob/master/mts/mts.go#L32-L51). With metrics updated this way, you may build your Heka message as provided in your example.

**Comment by elemoine** [comment]
@marcin-krolik Yes, this is basically what is done in Olivier's [branch](https://github.com/intelsdi-x/snap-plugin-publisher-heka/compare/master...obourdon:all_in_1).

Please pay attention to the Heka message format that we are proposing and tell us if you agree with it. Thanks!

**Comment by marcin-krolik** [comment]
@elemoine I'm not familiar with Heka, thus I can't say if it's correct or not. What I've noticed, is that `Payload` still contains dynamic elements - I don't know if it's needed or desired to be this way.

**Comment by elemoine** [comment]
The proposed message format is not exactly correct in the issue description. Here is a correct message:

```rst
Uuid: 39EF1568-7747-4016BC77-B5AF32492
:Timestamp: 2016-06-21 07:19:51.904164352 +0000 UTC
:Type: snap.heka
:Logger: snap.heka.logger
:Severity: 6
:Payload: [{"namespace":[{"Value":"intel","Description":"","Name":""},
                         {"Value":"procfs","Description":"","Name":""},
                         {"Value":"disk","Description":"","Name":""},
                         {"Value":"vda1","Description":"","Name":"disk"},
                         {"Value":"merged_read","Description":"","Name":""}],
            "last_advertised_time":"0001-01-01T00:00:00Z",
            "version":0,"config":null,"data":0,
            "tags":{"plugin_running_on":"lma-uaso2"},
            "Unit_":"","description":"","timestamp":"2016-06-21T07:19:51.83649625Z"}]
:EnvVersion: <nil>
:Pid: 219
:Hostname: lma-uaso2
:Fields:
    | name:disk type:0 representation: value:vda1
    | name:plugin_running_on type:0 representation: value:lma-uaso2
    | name:dimensions type:0 representation: value:disk,plugin_running_on
    | name:name type:0 representation: value:intel.procfs.disk.merged_read
    | name:value type:3 representation: value:0
    | name:timestamp type:2 representation: value:1.4664935918365e+18
```

In the Payload the "vda1" namespace element is dynamic (its name is "disk").

Since this element is converted to a Field in the Heka message we could indeed remove it from the namespace in the Payload. But the Payload is just a JSON representation of the Snap metric, so I don't we want to change it. And our plan is to make the addition of the Payload optional, as it is only useful for debugging.

Thanks for your feedback.

**Comment by candysmurf** [comment]
May I know the use cases for the proposed "dimensions" field if you define it as an array of tags?

**Comment by obourdon** [comment]
@candysmurf yes we will be using all tags and dynamic elements as part of the dimensions fields

This way the information, propagated from Heka to InfluxDB for instance will enforce proper "tagging" in the InfluxDB sense and we will be able to properly graph associated data within Grafana. 

With my [modified branch version of Heak published plugin](https://github.com/obourdon/snap-plugin-publisher-heka/tree/all_in_1) and considering also a [modified version of the disk collector](https://github.com/obourdon/snap-plugin-collector-disk/tree/all_in_1) which consist if making metrics dynamic we are able to store and graph all disk metrics properly in InfluxDB as well as present them in a nice and easy way in a Grafana dashboard, allowing the user to chose which disk (dimension) to display using a choice menu. HTH

**Comment by candysmurf** [comment]
@obourdon, It sounds a good addition. Please free to submit a PR once you're done your testing. thank you. I still have one more question for you. What're you going to use "dimensions" for in InfluxDB as you have all of them as fields already?

**Comment by elemoine** [comment]
@candysmurf This is a good question. Note that `Fields` in the Heka message also includes the name and the value of the metric, in `name` and `value` fields, respectively. So we need a way to distinguish fields that are to be used as tags in InfluxDB. Does that make sense?

**Comment by candysmurf** [comment]
@elemoine, yes, it makes sense if you have a use case for it. As you said, the payload is purely for a debugging purpose or it helps to get all in a JSON format. 

JFYI, Snap's namespace, and value pairs become a dropdown item in Grafana automatically. Items are more searching friendly when they're in key and value pairs.
