### ISSUE TITLE
Enable Travis for this plugin

### ISSUE THREAD

**Issue by elemoine** [intelsdi-x/snap-plugin-publisher-heka#13]
The Snap framework and Snap plugins use Travis for CI. We should enable Travis for the Heka plugin as well.

**Comment by nanliu** [comment]
See #15. @candysmurf we need to move the heka compile out of .travis.yml into the build.sh. I was unable to release this plugin as part of the 0.15 release because build.sh was not stand alone.

**Comment by candysmurf** [comment]
@nanliu, I'll work on this feature this week. thanks for letting me know.

**Comment by candysmurf** [comment]
@elemoine,  PR 15 is merged and addressed this issue.
