### ISSUE TITLE
Schedule for release in snap 0.16

### ISSUE THREAD

**Issue by nanliu** [intelsdi-x/snap-plugin-publisher-heka#16]
Per comment in #15, because we don't have a standalone build.sh script, this plugin was not released for the snap 0.15 release. We need to resolve #15, and move the heka build logic out of travis ci into build.sh so we can target release for snap 0.16.

**Comment by candysmurf** [comment]
#15 is merged. It addressed this issue.

**Comment by elemoine** [comment]
@candysmurf can you please confirm that the Heka plugin will be released with the Snap 0.16 release? Thanks.

**Comment by nanliu** [comment]
@elemoine, we already changed the release build to include the heka plugin and I expect to have it packaged for the 0.16 release.

**Comment by elemoine** [comment]
Ok, thanks for confirming.

On a different topic I'd be interested to know what you use for creating releases of Snap. Do you have some script/CI to build Snap and plugins and package them for the release? Thanks.
