### ISSUE TITLE
Is binary file of heka plugin available?

### ISSUE THREAD

**Issue by katarzyna-z** [intelsdi-x/snap-plugin-publisher-heka#25]
Is binary file of heka plugin available?

Trying to get the binary file with this command `wget http://snap.ci.snap-telemetry.io/plugins/snap-plugin-publisher-heka/latest/linux/x86_64/snap-plugin-publisher-heka`  I receive `404 Not Found` error. The [release page](https://github.com/intelsdi-x/snap-plugin-publisher-heka/releases) is also empty.

**Comment by nanliu** [comment]
This has been addressed by #29 and #30. From this point forward, releases should work as expected. Please reopen the issue if you find any other problems.
