### ISSUE TITLE
Plugin no longer builds

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap-plugin-publisher-heka#4]
This plugin no longer builds. No Godeps were pinned for `github.com/mozilla-services/heka`, so I'm not clear on what version of this package was used for testing, and the current HEAD of this package does not build when trying to build the plugin.

**Comment by candysmurf** [comment]
Heka requires to have its binary on the GOPATH. Basically we need to source "env.sh" file as below:

#!/usr/bin/env bash

# if the environment has been setup before clean it up
if [ $GOBIN ]; then
    PATH=$(echo $PATH | sed -e "s;\(^$GOBIN:\|:$GOBIN$\|:$GOBIN\(:\)\);\2;g")
fi

BUILD_DIR=$PWD/build
export CTEST_OUTPUT_ON_FAILURE=1
export GOPATH=$BUILD_DIR/heka
export LD_LIBRARY_PATH=$BUILD_DIR/heka/lib
export DYLD_LIBRARY_PATH=$BUILD_DIR/heka/lib
export GOBIN=$GOPATH/bin
export PATH=$GOBIN:$PATH

**Comment by elemoine** [comment]
I tried to follow the instructions of the "Building from source" section of README.md and that did not work for me either. But I did manage to build the plugin using the following method:

```
$ cd /tmp
$ git clone https://github.com/mozilla-services/heka
$ cd heka
$ source build.sh  # this sets the env (GOPATH in particular) and build Heka
$ echo $GOPATH
/tmp/heka/build/heka
$ go get github.com/intelsdi-x/snap-plugin-publisher-heka
$ cd heka/src/github.com/intelsdi-x/snap-plugin-publisher-heka/
$ make all
$ ls build/rootfs
snap-plugin-publisher-heka
```

The README should probably be updated.

**Comment by candysmurf** [comment]
@elemoine, It appears that "source build.sh" is better than "source env.sh". I'll update the README. thank you.

**Comment by elemoine** [comment]
Thanks.

**Comment by candysmurf** [comment]
PR#15 addressed this issue.
